Repository ds300/lazyrepo, pull requests merged in 2023-04, with the labels that each got.

#64 add publish script
  .eslintrc.cjs
  .github/workflows/publish-new.yml
  scripts/lib/exec.js
  scripts/publish-canary.js
  scripts/publish-new.js
  thoughts.md
Labels: internal

#65 Set latest tag when publishing 0.0.0-alpha releases
  README.md
  index.d.ts
  scripts/publish-new.js
  src/config/config-types.d.ts
  src/config/config.js
  src/config/validateConfig.js
  src/types.d.ts
  test/TaskGraph.test.ts
  test/integration/runIntegrationTests.ts
Labels: patch

#67 Improve lazy inherit
  CONTRIBUTING.md
  package.json
  scripts/pack-test-version.js
  src/commands/inherit.js
  src/commands/run.js
  src/config/config.js
  src/execCli.js
  src/runTask.js
  test/extractInheritMatch.test.ts
  test/integration/config.test.ts
  test/integration/inherit.test.ts
  test/integration/run.test.ts
  test/integration/runIntegrationTests.ts
Labels: minor

#68 Allow ignoring workspaces
  .eslintrc.cjs
  scripts/pack-test-version.js
  src/config/config-types.d.ts
  src/config/config.js
  src/config/validateConfig.js
  src/project/Project.js
  test/integration/ignoreWorkspaces.test.ts
Labels: minor

#70 add check-pr-labels script
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr-labels.yml
  package.json
  pnpm-lock.yaml
  scripts/check-pr-labels.js
Labels: internal

#71 Improve check-pr-labels script
  .github/workflows/check-pr-labels.yml
  scripts/check-pr-labels.js
Labels: internal

#73 don't run check-pr-labels on merged/closed PRs
  .github/workflows/check-pr-labels.yml
  scripts/check-pr-labels.js
Labels: internal

#72 Exit after successfully running commands
  src/execCli.js
Labels: patch

#74 Fix publishing script.
  scripts/publish-new.js
Labels: patch

#75 Fix top-level inherit commands
  src/commands/inherit.js
  test/integration/inherit.test.ts
Labels: patch

#76 run prettier before committing changelog
  CHANGELOG.md
  scripts/publish-new.js
Labels: internal

#77 Add colors to the diff depending on the diff kind.
  src/logger/InteractiveLogger.js
  src/logger/RealtimeLogger.js
  src/logger/formatting.js
  src/runTask.js
  src/types.d.ts
Labels: patch

#82 add pr-label-enforcer worker to repo
  package.json
  pnpm-lock.yaml
  pr-label-enforcer/src/index.ts
  pr-label-enforcer/wrangler.toml
Labels: internal

#83 Rename "tasks" config option to "scripts"
  README.md
  src/TaskGraph.js
  src/commands/inherit.js
  src/commands/run.js
  src/config/config-types.d.ts
  src/config/config.js
  src/config/validateConfig.js
  src/execCli.js
  src/manifest/computeManifest.js
  src/manifest/getInputFiles.js
  src/runTask.js
  src/types.d.ts
  test/TaskGraph.test.ts
  test/integration/config.test.ts
  test/integration/globbing.test.ts
  test/integration/help.test.ts
  test/integration/ignoreWorkspaces.test.ts
  test/integration/independent.test.ts
  test/integration/inherit.test.ts
  test/integration/run.test.ts
  test/integration/top-level.test.ts
Labels: major

#85 Log full diff + manifest on CI
  package.json
  pnpm-lock.yaml
  src/isCi.js
  src/logger/InteractiveLogger.js
  src/logger/RealtimeLogger.js
  src/manifest/computeManifest.js
  src/runTask.js
  src/types.d.ts
  test/integration/ci-logging.test.ts
  test/integration/runIntegrationTests.ts
Labels: minor

#86 Support workspace overrides
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
  src/config/config-types.d.ts
  src/config/config.js
  src/config/validateConfig.js
  test/config.test.ts
  test/integration/workspaceOverrides.test.ts
  test/setup.ts
  test/validateConfig.test.ts
Labels: minor

#90 log.fail should throw
  .eslintrc.cjs
  src/TaskGraph.js
  src/cli.js
  src/commands/clean.js
  src/commands/inherit.js
  src/commands/init.js
  src/commands/run.js
  src/config/config.js
  src/config/resolveConfig.js
  src/execCli.js
  src/logger/InteractiveLogger.js
  src/logger/LazyError.js
  src/logger/RealtimeLogger.js
  test/ManifestContstructor.test.ts
  test/TaskGraph.test.ts
  test/integration/config.test.ts
Labels: patch

#92 Cache console output
  src/commands/clean.js
  src/config/config-types.d.ts
  src/config/config.js
  src/config/validateConfig.js
  src/logger/RealtimeLogger.js
  src/manifest/createLazyWriteStream.js
  src/naiveRimraf.js
  src/rimraf.js
  src/runTask.js
  test/integration/ci-logging.test.ts
  test/integration/config.test.ts
  test/integration/dependent.test.ts
  test/integration/globbing.test.ts
  test/integration/ignoreWorkspaces.test.ts
  test/integration/independent.test.ts
  test/integration/inherit.test.ts
  test/integration/log-caching.test.ts
  test/integration/run.test.ts
  test/integration/runIntegrationTests.ts
  test/integration/top-level.test.ts
  test/integration/workspaceOverrides.test.ts
Labels: minor

#94 URL-safe paths based on script names
  src/config/config.js
  test/integration/ci-logging.test.ts
  test/integration/config.test.ts
  test/integration/dependent.test.ts
  test/integration/globbing.test.ts
  test/integration/ignoreWorkspaces.test.ts
  test/integration/independent.test.ts
  test/integration/inherit.test.ts
  test/integration/log-caching.test.ts
  test/integration/run.test.ts
  test/integration/top-level.test.ts
  test/integration/workspaceOverrides.test.ts
Labels: patch
